sudo: false
cache: cargo
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
install:
    - rustup component add clippy
 
script:
    - cargo clippy -- -D clippy::all
    - cargo build
    - cargo test
