max_width= 80
comment_width=80
merge_imports=true
unstable_features=true
wrap_comments = true
condense_wildcard_suffixes=true
format_code_in_doc_comments=true
format_macro_matchers=true
format_strings=true
struct_field_align_threshold=20
enum_discrim_align_threshold=20
use_field_init_shorthand=true
version="Two"